# Atom publisher information
#
author:
  name: The Cleveland Ruby Brigade
  uri: http://clerb.org
  email: info@clerb.org

# If you want to use the Disqus service (http://disqus.com) to display
# comments on your site, register a Disqus account and then specify your
# site's short name here. A comment form will automatically be added to
# the bottom of your pages.
#
disqus_short_name: clerb

# The remaining configuration settings are set separately in development
# (i.e. when running on your local workstation) and production (when running
# on your live server).
#
# content - the root directory where nesta will look for your article files.
# Should contain "articles", "categories" and "attachments" subdirectories
# that contain your actual content.
#
# google_analytics_code - set this if you want Google Analytics to track
# traffic on your site. Probably best not to set it in development mode.
#
development:
  cache: false
  content: content

production:
  cache: true
  content: content
  # google_analytics_code: "UA-???????-?"
